<!--
* < Concept-Name: ApplicationAPISettings >
* This component handles the creation of API-keys. It is embedded into "ApplicatoinDashboardWrapper". There the display is 
limited to creators of an application and therefor will not show for regular users.
Once given a name, a prompt will trigger and display the "ApiKeyResponse" found in the components-folder. The actual key
will only be displayed once. The listing only contains the names and not the key itself. This should not be changed for 
security purposes. The key can be copied to the clipboard via a button on the prompt.

* @author: anonymous
* @version 1.0
* @since   2023-23-01
-->

<template>
  <GridContentComponent :name="'APISettings'">
    <div class="miniTable_wrapper">
      <h4>Add new API-Key</h4>
      <InputComponent @enter="newKeyName" :removeTextafterSoftProgress="true"> </InputComponent>
      <div v-if="allAPIKeys.length > 0">
        <div v-for="keys in allAPIKeys" :key="keys" class="miniTable_row">
          <p>{{ keys.name }}</p>
          <span class="miniTable_row_rightCluster">
            <p @click="removeKey(keys.id)" class="miniTable_pointer">❌</p>
          </span>
        </div>
      </div>
      <div v-else>
        <p>There are no active API-Keys in this application.</p>
      </div>
    </div>
  </GridContentComponent>
  <Transition name="key-screen">
    <ApiKeyResponse v-if="showApiPlainText">
      <p>{{ apiMessage }}</p>
      <button @click="ctc(apiMessage)">Copy</button>
      <button @click="showApiPlainText = false">Ok</button>
    </ApiKeyResponse>
  </Transition>
</template>

<!--
* APIKeyResponse was created only for this component but the copy- and and ok-button were separated to make future use
of the ApiKeyResponse elsewhere possible. It can be found in: ./components.

* The key itself is generated in the backend after an api-request. It is not stored anywhere in the frontend.
* By default a "Standard" key is generated by the backend and displayed opon creation of an application.
-->
<script>
import { mapState, mapActions } from "vuex";
import GridContentComponent from "@/components/GridContentComponent.vue";
import InputComponent from "@/components/Input/InputComponent.vue";
import api from "@/apiService.js";
import ApiKeyResponse from "@/components/ApiKeyResponse.vue";

export default {
  name: "APISettings",
  components: {
    GridContentComponent,
    InputComponent,
    ApiKeyResponse
  },

  data() {
    return {
      showApiPlainText: false,
      apiMessage: ""
    };
  },
  computed: {
    allAPIKeys() {
      if (this.currentApplication?.reducedApiKeys?.length >= 0) return this.currentApplication?.reducedApiKeys;
      return [];
    },

    ...mapState({
      currentApplication: (state) => state.currentApplication
    })
  },

  methods: {
    // System function of copying something to the clipboard.
    ctc(value) {
      navigator.clipboard.writeText(value);
    },

    /* The key name must have 2 letters or more. This limitation is arbitrary and is in no way a requirement by the backend.
    The same is true for duplicate names. These are not filtered nor forbidden from the backend.
    */
    async newKeyName(apiKeyName) {
      if (apiKeyName.length > 2) {
        const keyResponse = await api.postString(`api/v1/applications/${this.currentApplication.id}/apikeys`, apiKeyName);
        this.apiMessage = keyResponse.clearTextApiKey;
        this.showApiPlainText = true;
        this.fetchcurrentApplication(this.currentApplication.id);
      } else {
        this.$store.commit("setNotification", { type: "error", message: "The name must have 2 letters minimum." });
      }
    },

    // The "Standard" key can be deleted as well.
    async removeKey(apiKeyID) {
      await api.delete(`api/v1/applications/${this.currentApplication.id}/apikeys/${apiKeyID}`);
      this.fetchcurrentApplication(this.currentApplication.id);
    },

    ...mapActions({
      fetchcurrentApplication: "fetchcurrentApplication"
    })
  }
};
</script>

<style lang="scss">
.responseButtons {
  display: grid;
}
</style>
